### ISSUE TITLE
Command 'sshfs.*' not found

### ISSUE THREAD

**Issue by jack-guy** [SchoofsKelvin/vscode-sshfs#1]
Hi, thanks for making this extension! I'm really excited to try it out!

Unfortunately, any `sshfs: whatever` command I run gives me an error in the latest version of VS Code (1.23):

> command 'sshfs.new' not found

Are the commands correctly registered in the extensions API?

**Comment by thijndehaas** [comment]
Same problem here..

**Comment by SchoofsKelvin** [comment]
I didn't properly specify the activationEvents in the package.json, resulting in the extension (and thus the commands) not being loaded for commands. I've published the fix (in version 1.3.2) to the marketplace.

**Comment by weswithley** [comment]
Same problem +1.
command 'sshfs.connect' not found, ( extension version 1.7.1 )
Thanks.

**Comment by SchoofsKelvin** [comment]
Interesting, the activationEvent contains that command, and the command gets properly registered.

What causes the error to appear, and how often does this happen?

**Comment by weswithley** [comment]
Hi,

my steps flow as below :

go preference with VS Code and set my host up.
command + shift + p & choose " connect a SSH FS as workspace folder".
and VS code just shows that error message to me.
it always happened with every time i use it.
or maybe something wrong with my setting?
my setting as below :
"sshfs.configs": [ { 
"root": "~/root", 
"host": "xx.xx.xx.xx", 
"port": 22, 
"username": "root", 
"password": "password"
} ]

Thanks for help. ^^

**Comment by SchoofsKelvin** [comment]
I've been able to reproduce it (only) once, and reloading the window fixed it. Even though vscode's logs showed it had started the extension, it seemed like it didn't.

Which version of the extension are you using?

**Comment by stratusjerry** [comment]
vscode: 1.25.0
SSH FS: 1.9.2
In developer tools, I see this line preceding the error:
`log.ts:159  INFO standard startup Object
extensionService.ts:892 Activating extension 'Kelvin.vscode-sshfs' failed: Cannot read property 'toLowerCase' of undefined.
w._logMessageInConsole @ extensionService.ts:892
notificationsAlerts.ts:40 Error: command 'sshfs.connect' not found`

**Comment by weswithley** [comment]
Hi, SchoofsKelvin,

I changed the version of **Vscode-sshfs** from **1.7.1** to **1.9.2**,
and the `_command 'sshfs.connect' not found_` doesn't show out anymore,
looks like the problem resolved,
maybe this issue could be closed?

btw,
pity that i still can't connect to my office server by **Vscode-sshfs**,
but using the `ssh root@xx.xx.xx.xx` connection with command-line is fine,
i think maybe that's my server setting problems,
so, i would go ask to my partners in these few days,
if any further infos,
i would let you know asap.

Thanks for your great help.

**Comment by SchoofsKelvin** [comment]
Since this bug doesn't seem to show up anymore, I'll close this issue.

> pity that i still can't connect to my office server by Vscode-sshfs,
> but using the ssh root@xx.xx.xx.xx connection with command-line is fine,

Feel free to open a new issue for that. It might (also) be an issue with the config, and/or the fact that I don't make use of `~/.ssh/config` yet.

**Comment by adnrcddly** [comment]
I am having this issue as well. I am running VSCode 1.25.1 and SSH FS 1.9.2 and it can't find any of the extensions to actually run. So my config looks good, but it won't even attempt to connect because .connect isn't found.

I have uninstalled, restarted, reinstalled, etc. Nothing has worked yet.

**Comment by baterson** [comment]
I have the same issue. Extension was working fine one day, next day it stops. With errors `command 'sshfs.<command_name>' not found` . 
VSCode Version 1.26.1 (1.26.1) . 
SSH FS 1.9.2 .

**Comment by hudson940** [comment]
I have the same issue. 'sshfs.*' not fount. I'm using vs-code ver: 1.26.1 and sshfs ver: 1.9.2

**Comment by zswanson** [comment]
Similar, exists on sshfs 1.9.2 and vs-code version 1.27.1 (user setup version) and running in Windows 10.

**Comment by AchmadFathoni** [comment]
Also happen on SSHFS 1.10.0, VSCODE 1.28.1, Ubuntu 16.04

**Comment by SchoofsKelvin** [comment]
Does the problem keep occurring after restarting vscode (or your pc) ?

**Comment by adnrcddly** [comment]
Deleting my config and entering it new corrected the issue for me

**Comment by SchoofsKelvin** [comment]
Closing due to lack of activity

**Comment by dwarburt** [comment]
I'm getting this now on Fedora 29, vscode 1.28.2, kelvin.vscode-sshfs-1.11.1. Restarting and reloading don't help, nor does deleting and recreating the configuration. I'll try to debug it a bit.

**Comment by pikuorguk** [comment]
> Edit 1: My problem was that I had tried to fill out the settings directly instead of generating it and left out the name.
> 
> Edit 2: The reason I got it wrong was because I was following along with the JSON object in the default settings, which doesn't have a name.

Same for me, the example config isn't quite correct. Using the VS Code ctrl-shift-P method works OK.

I'm using it on my Chromebook with the experimental Linux environment btw.

**Comment by kwinz** [comment]
Version 1.28.2 Using this plugin for the first time. Got this error. A bit frustrating.
Restarting Visual Studio Code resolved it.

**Comment by SchoofsKelvin** [comment]
All configurations need the `name` field, along with either `putty` and/or a combination of `host`, `username`, ...

The documentation might not be the best right now, but within one configuration object, assume all the fields above are still present (unless overwritten in lines that came afterwards)

**Comment by rehovey** [comment]
On Mac High Sierra VS Code 1.29 SSHFS v1.11.1 (latest in Marketplace) - I had to ensure I was using the 'name' property and restart VS Code but it is working for me.

**Comment by LogX7** [comment]
+1

**Comment by kshkaran2k** [comment]
I am also getting `command 'sshfs.new' not found` error.
I have configured to access my code present in AWS EC2 instance. I have restarted the code also after the installation of the extension.

I am using Windows 7, VS Code Version: 1.26.1, Architecture: x64 with SSH-FS version 1,11,2 (directly download and installed from VS Code).

**Comment by lifedup** [comment]
+1 using vs code version 1.29.1 and windows 10.  It was working until I updated vs code.

**Comment by lifedup** [comment]
> I am also getting `command 'sshfs.new' not found` error.
> I have configured to access my code present in AWS EC2 instance. I have restarted the code also after the installation of the extension.
> 
> I am using Windows 7, VS Code Version: 1.26.1, Architecture: x64 with SSH-FS version 1,11,2 (directly download and installed from VS Code).

Make sure you have the keys "putty" and "name" in your config or it will not work.

**Comment by bluecamel** [comment]
Thanks so much, @lifedup.  It works now.

**Comment by SchoofsKelvin** [comment]
> > I am also getting `command 'sshfs.new' not found` error.
> > I have configured to access my code present in AWS EC2 instance. I have restarted the code also after the installation of the extension.
> > I am using Windows 7, VS Code Version: 1.26.1, Architecture: x64 with SSH-FS version 1,11,2 (directly download and installed from VS Code).
> 
> Make sure you have the keys "putty" and "name" in your config or it will not work.

Thanks to this, I was able to figure out what caused this bug. It should be fixed now (2fca495) under version 1.12.2 of the extension. The extension will now ignore nameless configurations, and give then a random name in the background.

**Comment by lopugit** [comment]
@SchoofsKelvin I'm still getting this error on this branch https://github.com/SchoofsKelvin/vscode-sshfs/tree/feature/search and on vscode-insiders v1.34.0

**Comment by SchoofsKelvin** [comment]
@lopugit Does this error only happen when using the search branch?
